name: simple_speed_dial
description: A simple speed dial for Flutter. You can use as many speed dial options as you want. You can use labels next to the speed dial options. Colors of every fab can be set.
version: 0.1.7
homepage: https://github.com/janoschp/simple_speed_dial

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 1.0.4
